# -*- coding: utf-8 -*-
# Copyright (c) 20016-2016 The Cloudsoar.
# See LICENSE for details.

"""
"""

ERROR_CODE_OFFSET = 20000

SUCCESS = 0
FAIL = ERROR_CODE_OFFSET
MAX_ERROR_CODE = ERROR_CODE_OFFSET +10000


UNCAUGHT_EXCEPTION_ERR = ERROR_CODE_OFFSET + 1


AUTHEN_ERROR = ERROR_CODE_OFFSET + 100
INVALID_TOKEN_ERR      = AUTHEN_ERROR + 1                # 无效的token
ERR_LOGIN_TIMEOUT      = AUTHEN_ERROR + 2                # 登录超时
USER_UN_LOGIN_ERR      = AUTHEN_ERROR + 3                # 用户未登录
ERR_ACCESS_IDNOTEXIST  = AUTHEN_ERROR + 4                # access_uuid不存在
ERR_NO_TOKEN_PARAM     = AUTHEN_ERROR + 5                # 缺少token
ERR_TIME_MISMATCH      = AUTHEN_ERROR + 6                # 时间偏移超过限制范围

ERR_TIMESTAMP_REPEAT   = AUTHEN_ERROR + 7                # 时间戳重复，调用太频繁或非法调用 

PERMISSION_DENIED_ERR  = AUTHEN_ERROR + 8                # 用户权限不够
ERR_UNDEFINED_RING     = AUTHEN_ERROR + 9                # 未定义的ring
NO_SUCH_GROUP_ERR      = AUTHEN_ERROR + 10               # 分组不存在
NO_SUCH_USER_ERR       = AUTHEN_ERROR + 11               # 用户不存在
INVALID_PASSWORD_ERR   = AUTHEN_ERROR + 12               # 密码错误
ERR_ACCESS_AUTHENFAIL  = AUTHEN_ERROR + 13               # 密钥未通过验证




COMMON_ERR = ERROR_CODE_OFFSET + 200
FILE_OPERATE_ERR = COMMON_ERR + 1
CALL_REMOTE_METHOD_ERR = COMMON_ERR + 2
REMOTE_SERVICE_ABNORMAL_ERR = COMMON_ERR + 3
SERVER_IS_DISCONNECT_ERR = COMMON_ERR + 4     # 服务器连接断开

ERR_SERVICE_INACTIVE = COMMON_ERR + 5
INTERNAL_OPERATE_ERR = COMMON_ERR + 6
INTERNAL_EXCEPT_ERR = COMMON_ERR + 7
PERMISSION_DENIED_ERR = COMMON_ERR + 8
ERR_METHOD_CONFLICT = COMMON_ERR + 10
RESULT_FORMAT_INVALID = COMMON_ERR + 11
INVALID_PARAM_ERR = COMMON_ERR + 12
INVALID_RESULT_DATA_ERR = COMMON_ERR + 13
INVALID_JSON_DATA_ERR = COMMON_ERR + 14

CONFIG_OUT_OF_LIMIT_ERR = COMMON_ERR + 50                # 用户输入超出配置限制
DATE_FAMAT_IS_INVALID = COMMON_ERR + 51                  # 日期格式不合法
PARAME_IS_INVALID_ERR = COMMON_ERR + 52                  # 参数不合法
CERT_NOT_EXIST_ERR = COMMON_ERR + 53                     # 参数不合法


API_ERR = ERROR_CODE_OFFSET + 2000
INVALID_PROJECT_INFO_ERR = API_ERR + 1
INVALID_GROUP_ERR = API_ERR + 1
INVALID_STACK_NAME_ERR = API_ERR + 2

LOG_FILE_NOT_EXIST_ERR = API_ERR + 7
CREATE_CRON_SCHEDULE_FAIL = API_ERR + 500
CREATE_INTERVAL_SCHEDULE_FAIL = API_ERR + 501
SEND_EMAIL_FAIL_ERR = API_ERR + 600


REMOTE_API_ERR = ERROR_CODE_OFFSET + 3000
CALL_REMOTE_API_FAIL_ERR = REMOTE_API_ERR + 0  # 通过接口取得数据不合法--转换成json失败
USER_RESPONSE_DATA_INVALID_ERR = REMOTE_API_ERR + 1  # 通过USER接口取得数据不合法--转换成json失败
DEPLOY_RESPONSE_DATA_INVALID_ERR  = REMOTE_API_ERR + 1  # 通过DEPLOY接口取得数据不合法--转换成json失败


UPGRADE_ERR = ERROR_CODE_OFFSET + 4000
UPGRADE_FAIL_ERR = UPGRADE_ERR + 1
DO_NOT_NEED_UPGRADE_ERR = UPGRADE_ERR + 2


WORK_FLOW_ERR = ERROR_CODE_OFFSET + 6000
WORK_INFO_INVALID_ERR = WORK_FLOW_ERR + 1
TASK_TIMEOUT_ERR = WORK_FLOW_ERR + 2
TASK_ALREADY_EXIST_ERR = WORK_FLOW_ERR + 3


ETCD_ERR = ERROR_CODE_OFFSET + 7000
ETCD_EXCEPTION_ERR = ETCD_ERR + 1
ETCD_CONNECT_FAIL_ERR = ETCD_ERR + 2     # etcd连接失败
ETCD_KEY_NOT_FOUND_ERR = ETCD_ERR + 3    # key不存在
ETCD_DIR_EXIST_ALREADY_ERR = ETCD_ERR + 4    # 目录已经存在
ETCD_MKDIR_FAIL_ERR = ETCD_ERR + 4    # 创建目录失败
ETCD_CREATE_KEY_FAIL_ERR = ETCD_ERR + 5    # 创建key失败
ETCD_UPDATE_FAIL_ERR = ETCD_ERR + 5    # etcd更新失败

DEPLOY_ERR = ERROR_CODE_OFFSET + 8000
PROJECT_IS_INVALID_ERR = DEPLOY_ERR + 1   # 项目无效
CONFIGURE_IS_INVALID_ERR = DEPLOY_ERR + 2   # 配置无效
TEMPLATE_IS_INVALID_ERR  = DEPLOY_ERR + 3   # 模板无效